services:
  qgis-server:
    image: "qgis/qgis-server:stable"
    platform: linux/amd64 # think this is neededa
    environment:
      # Do not run the embedded copy of nginx
      SKIP_NGINX: "true"
      # Improve rendering performance
      QGIS_SERVER_PARALLEL_RENDERING: "true"
      QGIS_SERVER_MAX_THREADS: 4
      # Limit the maximum size returned by a GetMap
      QGIS_SERVER_WMS_MAX_HEIGHT: 5000
      QGIS_SERVER_WMS_MAX_WIDTH: 5000
      PYTHONPATH: "/usr/share/qgis/python/plugins"
    networks:
     - qgis-server-net
    volumes:
     # Data should be mount RO when working
     # with GeoPackages and more than one QGIS container
     - ./src/:/app
     - ./test/data:/io/data:ro
     - ./plugins:/io/plugins
     - ./fonts:/usr/share/fonts
     - ./svg:/var/lib/qgis/.local/share/QGIS/QGIS3/profiles/default/svg
     # - ./conf/pg_service.conf:/etc/postgresql-common/pg_service.conf:ro
    restart: always

networks:
  qgis-server-net: