services:
  preprocessing:
    image: "landwater-preprocessing"
    build: 
      context: preprocessing/
      dockerfile: Dockerfile.dev
    container_name: preprocessing
    platform: linux/amd64 # think this is neededa
    environment:
      # Do not run the embedded copy of nginx
      SKIP_NGINX: "true"
      # Improve rendering performance
      QGIS_SERVER_PARALLEL_RENDERING: "true"
      QGIS_SERVER_MAX_THREADS: 4
      # Limit the maximum size returned by a GetMap
      QGIS_SERVER_WMS_MAX_HEIGHT: 5000
      QGIS_SERVER_WMS_MAX_WIDTH: 5000
      PYTHONPATH: "/usr/share/qgis/python/plugins"
    volumes:
      - ../preprocessing:/workspaces:cached  
      - ../preprocessing/data/input:/workspaces/data/input
      - shared_data:/workspaces/data/output
    restart: unless-stopped
  
  rust:
    image: "mcr.microsoft.com/devcontainers/rust:1-1-bullseye"
    container_name: rust
    platform: linux/amd64 # think this is 
    entrypoint: [ "zsh", "-c", "while sleep 1000; do :; done" ]
    volumes:
      - ../rust:/workspaces:cached  
      - shared_data:/data:ro 

    restart: unless-stopped

volumes:
  shared_data: