[package]
name = "LandOrWater"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
env_logger = "0.11.6"
geo = "0.29.3"
geo-types = "0.7.15"
serde_json = "1.0.138"
shapefile = {version = "0.6.0", features=["geo-types"]}
